### ISSUE TITLE
Panic when called outside of cargo project / workspace

### ISSUE THREAD

**Issue by bjorn3** [nrc/cargo-src#221]
```
thread 'main' panicked at 'error parsing json from `cargo metadata`: Error("EOF while parsing a value", line: 1, column: 0)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:205
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:457
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:344
   6: rust_begin_unwind
             at libstd/panicking.rs:322
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: cargo_src::main
```

**Comment by nrc** [comment]
Thanks for filing this issue. This is a dup of #200, so closing.
